on:
  push:
    branches:
      - main

name: Serverless Deploy

jobs:
  deploy:
    name: Serverless Deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Install Dependencies
        run: |
          yarn install

      - name: Deploy to aws
        run: yarn serverless deploy  --account ${{secrets.AWS_USER_NAME}}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}